### ISSUE TITLE
Redesign Blogs page

### ISSUE THREAD

**Issue by Kushagraw12** [Kushagraw12/Scee-Website#18]
**Is your feature request related to a problem? Please describe.**
The Blogs page does not look good right now.  It needs some creativity and redesigning.

**Describe the solution you'd like**
We need an image, followed by title of the blog, followed by the first 2-3 lines of the blog.
Also incorporate the name of the writer and the date in the preview. 

**Describe alternatives you've considered**
On the first look, the whole blog should not be visible. The 'continue reading' button should preview the whole blog along with the image. You are free to use any way to implement this solution. My suggestion would be to make a modal and toggle it using the 'continue reading' button. New suggestion are welcome!

**Additional context**
Please upload the image of your design before making a pr. If I feel that your pr is just to increase the number of prs for Hacktoberfest, I will simply mark them 'invalid'

**Comment by alkatrivedi** [comment]
I would like to work on it. May I?

**Comment by Kushagraw12** [comment]
Yeah sure go ahead @alkatrivedi

**Comment by alkatrivedi** [comment]
On it. Thank You!

**Comment by alkatrivedi** [comment]
I did some changes, here I'm putting some snapshots. I hope it's fine.
![Capture](https://user-images.githubusercontent.com/58396306/94599854-ae7e2600-02ae-11eb-8533-90650a15f60c.JPG)

After pressing Continue reading button it's something like
![Capture1](https://user-images.githubusercontent.com/58396306/94599889-bb9b1500-02ae-11eb-97d5-752eb95c99df.JPG)

For now I have used lorem ipsum text on clicking Continue reading button. Please guide if I did anything wrong.

**Comment by alkatrivedi** [comment]
Also I have added the feature of 'read less' like after previewing whole blog 'Continue reading' button text will change to 'read less' clicking that user will get only four lines of text as before.

**Comment by alkatrivedi** [comment]
Hey! Please do let me know, can I make PR? Whatever I did is it fine?

**Comment by Kushagraw12** [comment]
@alkatrivedi it looks good, can you share the ss with the "read less" button please?
Rest it looks good! 
Thanks!

**Comment by alkatrivedi** [comment]
Ya sure! Here it is

![Capture](https://user-images.githubusercontent.com/58396306/94664925-24bf6e80-0329-11eb-97cc-d61c526890ef.JPG)

**Comment by Kushagraw12** [comment]
Yeah, this looks good! Make a pr! @alkatrivedi

**Comment by alkatrivedi** [comment]
Thank you @Kushagraw12. May I make my PR tomorrow so that it may count on my hactoberfest contribution?

**Comment by alkatrivedi** [comment]
Please review my PR #26. Thank you.

**Comment by alkatrivedi** [comment]
@Kushagraw12 Can you please review my PR #26 ?

**Comment by 72002sweta** [comment]
I can make it better if you allow me to.

**Comment by Kushagraw12** [comment]
> I can make it better if you allow me to.
Sorry this repo is no longer maintained.
